diary/config/routes.rb
Rails.application.routes.draw do
# creating the routes and settng the root to sessions new so that when 
# the app loads it goes to that page
root to: 'sessions#new'

resources :users, only: [:new, :create, :index, :show]

resource :session, only: [:new, :create, :destroy]

resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

diary/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

diary/app/models/event.rb
# The validation for each column and the relationship to user is done here

class Event <ApplicationRecord
belongs_to :user

validates :name, presence: true
validates :venue, presence: true
validates :date, presence: true
validates :description, presence: true
end

diary/app/models/user.rb
# This was taken from the auth example provided. The lenght of the username, password and its
# validation are defined. Verifying username and password.

class User < ApplicationRecord
  PASSWORD_LENGTH = (6..25)
  USERNAME_LENGTH = (5..15)

  validates_presence_of :username
  validates :username, length: USERNAME_LENGTH, uniqueness: true

  validates :password, length: PASSWORD_LENGTH, allow_nil: true

  has_many :events

  attr_reader :password

  def self.find_from_credentials(username, password)
    user = find_by(username: username)
    return nil unless user
    user if user.is_password?(password)
  end

  def is_password?(password_attempt)
    BCrypt::Password.new(password_digest).is_password?(password_attempt)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
end

diary/app/controllers/application_controller.rb
# This was used from the auth example provided in class. .
# Defining current user and finding  current user.

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def sign_in(user)
    session[:session_token] = SecureRandom.urlsafe_base64
    user.update!(session_token: session[:session_token])
  end

  def sign_out
    return unless current_user
    current_user.update!(session_token: nil)
    session.delete(:session_token)
  end

  def current_user
    @current_user ||= find_current_user
  end

  def find_current_user
    session_token = session[:session_token]
    session_token && User.find_by(session_token: session_token)
  end

  def ensure_signed_in
    return if current_user
    flash[:error] ='You must be signed in to this'
    redirect_to :root
  end

  def ensure_signed_out
    return unless current_user
    flash[:error] = 'You are already signed in'
    redirect_to users_path
  end
end

diary/app/controllers/events_controller.rb
# Defining methods for CRUD for the events.Ensureing user is signed in

class EventsController < ApplicationController

  before_action :ensure_signed_in
  before_action :load_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = current_user.events
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    
    if @event.save
      redirect_to events_path
    else
      render :action => :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to event_path
    else
      render :action => :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :venue, :date, :description)
  end

  def load_event
    @event = current_user.events.find(params[:id])
  end
end

diary/app/controllers/sessions_controller.rb
#This was adapted from the auth example provided
#Defining method to sign and sign out.
class SessionsController < ApplicationController

  before_action :ensure_signed_out, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    username = user_params[:username]
    password = user_params[:password]

    user = User.find_from_credentials(username, password)

    if user
      sign_in(user)
      flash[:notice] =''
      redirect_to events_path
    else
      flash[:error] = "User not found"
      @user = User.new(username: username)
      render :new
    end
  end

  def destroy
    sign_out
    flash[:notice] = "You signed out!"
    redirect_to new_session_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

diary/app/controllers/users_controller.rb
# The auth was adapted from the auth example provided.
# Defining methods to create and show users
class UsersController < ApplicationController

  before_action :ensure_signed_out, only: [:new, :create]
  before_action :ensure_signed_in, only: [:show, :index]

  def new
    @user = User.new
  end

  def create
    @user = User.new(create_params)

    if @user.save
      sign_in(@user)
      redirect_to events_path
    else
      flash[:error] = @user.errors.full_messages.join(', ')
      render :new
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def create_params
    params.require(:user).permit(:username, :password)
  end
end

diary/app/helpers/application_helper.rb
module ApplicationHelper
end

diary/app/views/events/_form.html.erb
<!-- This is where the form is being created. -->
<center>
    <div>
        <%= form_for @event do |form| %>
            <p><span class='tags'>Name of Event:</span>
                <%= form.text_field :name, placeholder: 'Name of Event',size:'37x1', :class => 'input' %>
            </p>
            <p><span class='tags'>Where was I:</span>
                <%= form.text_field :venue, placeholder: 'Venue',  size:'40x1',:class => 'input' %>
            </p>
            <p><span class='tags'>When was it:</span>
                <%= form.text_field :date, placeholder: 'Date', size:'40x1',:class => 'input' %>
            </p>
            <p class='tags'>My Memory:</p>
            <%= form.text_area :description, size: "80x12",:class => 'input' %>
                <br>
                <%= form.submit :class => 'buttonTo'%>
                    <% end %>
    </div>
</center>

diary/app/views/events/edit.html.erb
<!-- The edit page with the populated data -->
<center>
    <div>
        <h1>Edit My Event</h1>
        <%= render :partial => 'form' %>
            <%= link_to 'All My Events', events_path, :class =>'buttonTo' %>
    </div>
</center>

diary/app/views/events/index.html.erb
<center>
    <div>
        <h2>MY AMAZING EXPERIENCES</h2>
        <% @events.each do |event| %>
            <ul>
                <span class='event'><%= link_to event.name, event_path(event) %></span>
                <button>
                    <%= button_to 'Delete Event', event, :method => 'delete', :class =>'buttonTo' %>
                </button>
            </ul>
            <% end %>
                <%= link_to 'Add Event', new_event_path, :class =>'buttonTo' %>
    </div>
</center>

diary/app/views/events/new.html.erb
<center>
    <div>
        <h1>Add a New Event</h1>
        <%= render :partial => 'form' %>
            <%= link_to 'All My Events', events_path, :class => 'buttonTo' %>
    </div>
</center>

diary/app/views/events/show.html.erb
<link href="https://fonts.googleapis.com/css?family=Stalemate|Great+Vibes" rel="stylesheet">
<center>
    <div>
        <h2>What was it: <%= @event.name %></h2>
        <h2>Where was it : <%= @event.venue %></h2>
        <h2>When was it: <%= @event.date %></h2>
        <h2>MY Memory</h2>
        <div class='tag'>
            <%= @event.description %>
        </div>
        <%= link_to 'Edit Event', edit_event_path, :class => 'buttonTo' %>
            <%= link_to 'All Events', events_path, :class => 'buttonTo' %>
    </div>
</center>

diary/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Diary</title>
    <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
            <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <div class='header'>Diary-O-Billa</div>
    <!-- The user and the logout button i visible in all pages -->
    <!-- The codes were modified from the auth example provided to us -->
    <% if current_user %>
        <%= link_to current_user.username,
    events_path(current_user) %> is signed in
            <br>
            <%= button_to 'Log Out', session_path, method: :delete, :class => "buttonTo" %>
                <% end %>
                    <% if flash[:notice].present? %>
                        <div class='notice'>
                            <%= flash[:notice] %>
                        </div>
                        <% end %>
                            <% if flash[:error].present? %>
                                <div class='errors'>
                                    <b>Errors:</b>
                                    <%flash[:error] %>
                                </div>
                                <% end %>
                                    <%= yield %>
                                        <% if current_user %>
                                            <!--     <br><br>
    
    <%=link_to 'Lets Add a Memory', new_event_path %> -->
                                            <% end %>
</body>

</html>

diary/app/views/users/index.html.erb
<center>
    <div>
        <h2>Users</h2>
        <ul>
            <% @users.each do |user| %>
                <h3><%= link_to user.username, user_path(user) %><h3>
      <% end %>
    </ul>
  </div>
</center>

diary/app/views/users/new.html.erb
<center>
    <div>
        <h2> Create a New Account </h2>
        <%= form_for @user do |form| %>
            <p class='tags'>Username:</p>
            <%= form.text_field :username,
    placeholder: 'Username',
    required: true, 
    minlength: User::USERNAME_LENGTH.begin,
    maxlength: User::USERNAME_LENGTH.end, 
    :class => 'input' %>
                <br>
                <br>
                <p class='tags'>Password:</p>
                <%= form.password_field :password,
      placeholder: 'password',
      required: true,
      minlength: User::PASSWORD_LENGTH.begin,
      maxlength: User::PASSWORD_LENGTH.end, 
      :class => 'input' %>
                    <br>
                    <br>
                    <%= submit_tag 'Create Account!', :class =>'buttonTo' %>
                        <% end %>
                            <br>
                            <p class='tags'>Returning user?
                                <%=link_to 'Sign in',new_session_path %>
                            </p>
    </div>
</center>

diary/app/views/users/show.html.erb
<center>
    <div>
        <h1><%= @user.username %></h1> More info about this user
        <br>
        <%= link_to 'All users', users_path %>
    </div>
</center>